CREATE USER IF NOT EXISTS 'malik'@'172.18.201.103' IDENTIFIED BY 'festo';
GRANT ALL PRIVILEGES ON *.* TO 'malik'@'172.18.201.103' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT;

CREATE DATABASE IF NOT EXISTS festo;
USE festo;

CREATE